"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import {
  Archive, ArrowLeft, ChevronDown, ChevronRight, Copy, Download, FileText, Folder,
  Grid2X2, LayoutList, MoreHorizontal, Plus, Search, Settings2, Share2, Star,
  UsersRound, X,
} from "lucide-react";

type Page = { id: number; name: string; template: string; updated: string; updatedBy: string; favorite: boolean; description: string };
type Space = { id: number; name: string; description: string; color: string; favorite: boolean; pages: Page[]; updated: string };

const colors = [
  { name: "Violet", value: "bg-violet-500", soft: "bg-violet-50 text-violet-600" },
  { name: "Blue", value: "bg-blue-500", soft: "bg-blue-50 text-blue-600" },
  { name: "Rose", value: "bg-rose-500", soft: "bg-rose-50 text-rose-600" },
  { name: "Amber", value: "bg-amber-500", soft: "bg-amber-50 text-amber-600" },
  { name: "Emerald", value: "bg-emerald-500", soft: "bg-emerald-50 text-emerald-600" },
];
const templates = ["Blank Page", "Project Plan", "Meeting Notes", "PRD", "Research Notes", "Task Plan"];

function Modal({ children, onClose }: { children: React.ReactNode; onClose: () => void }) {
  return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/25 p-4 backdrop-blur-sm" role="dialog" aria-modal="true">
    <div className="relative w-full max-w-md rounded-2xl border border-slate-200 bg-white p-6 shadow-2xl shadow-slate-900/15">{children}<button onClick={onClose} aria-label="Close" className="absolute right-5 top-5 grid h-8 w-8 place-items-center rounded-lg text-slate-400 hover:bg-slate-100 hover:text-slate-700"><X className="h-4 w-4" /></button></div>
  </div>;
}

export function SpacesWorkspace() {
  const [spaces, setSpaces] = useState<Space[]>([]);
  const [activeSpace, setActiveSpace] = useState<number | null>(null);
  const [activePage, setActivePage] = useState<number | null>(null);
  const [showSpaceModal, setShowSpaceModal] = useState(false);
  const [showPageModal, setShowPageModal] = useState(false);
  const [spaceName, setSpaceName] = useState("");
  const [spaceDescription, setSpaceDescription] = useState("");
  const [color, setColor] = useState(colors[0].value);
  const [pageName, setPageName] = useState("");
  const [pageTemplate, setPageTemplate] = useState(templates[0]);
  const [pageSpace, setPageSpace] = useState<number | "">("");
  const [search, setSearch] = useState("");
  const [view, setView] = useState<"grid" | "list">("grid");
  const [filter, setFilter] = useState("All Spaces");
  const [sort, setSort] = useState("Recently Updated");

  const selectedSpace = spaces.find((space) => space.id === activeSpace);
  const selectedPage = selectedSpace?.pages.find((page) => page.id === activePage);
  const filteredSpaces = useMemo(() => {
    const term = search.toLowerCase();
    const matches = spaces.filter((space) => space.name.toLowerCase().includes(term) || space.description.toLowerCase().includes(term) || space.pages.some((page) => page.name.toLowerCase().includes(term)));
    const scoped = filter === "Favorites" ? matches.filter((space) => space.favorite) : filter === "Archived" ? [] : matches;
    return [...scoped].sort((a, b) => sort === "Name" ? a.name.localeCompare(b.name) : sort === "Most Pages" ? b.pages.length - a.pages.length : sort === "Favorites" ? Number(b.favorite) - Number(a.favorite) : b.id - a.id);
  }, [spaces, search, filter, sort]);

  function createSpace() {
    const name = spaceName.trim();
    if (!name) return;
    const item: Space = { id: Date.now(), name, description: spaceDescription.trim() || "No description yet.", color, favorite: false, pages: [], updated: "Just now" };
    setSpaces((current) => [item, ...current]);
    setSpaceName(""); setSpaceDescription(""); setColor(colors[0].value); setShowSpaceModal(false);
  }
  function createPage() {
    const name = pageName.trim();
    const target = typeof pageSpace === "number" ? pageSpace : activeSpace;
    if (!name || !target) return;
    const page: Page = { id: Date.now(), name, template: pageTemplate, updated: "Just now", updatedBy: "You", favorite: false, description: "Add a description to give this page more context." };
    setSpaces((current) => current.map((space) => space.id === target ? { ...space, updated: "Just now", pages: [page, ...space.pages] } : space));
    setPageName(""); setPageTemplate(templates[0]); setPageSpace(""); setShowPageModal(false); setActiveSpace(target); setActivePage(page.id);
  }
  function toggleSpaceFavorite(id: number) { setSpaces((current) => current.map((space) => space.id === id ? { ...space, favorite: !space.favorite } : space)); }
  function togglePageFavorite(id: number) { if (!activeSpace) return; setSpaces((current) => current.map((space) => space.id === activeSpace ? { ...space, pages: space.pages.map((page) => page.id === id ? { ...page, favorite: !page.favorite } : page) } : space)); }

  const openPageModal = () => { setPageSpace(activeSpace ?? ""); setShowPageModal(true); };
  const actionClass = "flex w-full items-center gap-2 rounded-lg px-3 py-2 text-left text-[12px] text-slate-600 hover:bg-violet-50 hover:text-violet-700";

  if (selectedPage && selectedSpace) return <main className="min-h-screen bg-[#fbfcff] px-5 py-6 text-slate-900 sm:px-9 lg:px-14">
    <div className="mx-auto max-w-5xl"><Link href="/spaces" onClick={(event) => { event.preventDefault(); setActivePage(null); }} className="inline-flex items-center gap-1.5 text-[12px] font-semibold text-slate-500 hover:text-violet-700"><ArrowLeft className="h-3.5 w-3.5" /> {selectedSpace.name}</Link>
      <div className="mt-8 rounded-2xl border border-slate-200 bg-white p-6 shadow-[0_12px_35px_-25px_rgba(15,23,42,.45)] sm:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><span className="rounded-full bg-violet-50 px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider text-violet-700">{selectedPage.template}</span><h1 className="mt-4 text-3xl font-bold tracking-tight">{selectedPage.name}</h1><p className="mt-2 text-sm text-slate-500">In {selectedSpace.name}</p></div><button onClick={() => togglePageFavorite(selectedPage.id)} className="grid h-10 w-10 place-items-center rounded-xl border border-slate-200 text-slate-400 hover:text-amber-500"><Star className={`h-4 w-4 ${selectedPage.favorite ? "fill-amber-400 text-amber-400" : ""}`} /></button></div>
        <p className="mt-8 max-w-2xl text-sm leading-6 text-slate-600">{selectedPage.description}</p><div className="mt-8 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-slate-50 p-4"><p className="text-[11px] font-semibold text-slate-400">COMMENTS</p><p className="mt-1 text-xl font-bold">0</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-[11px] font-semibold text-slate-400">LINKED TASKS</p><p className="mt-1 text-xl font-bold">0</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-[11px] font-semibold text-slate-400">LAST EDITED</p><p className="mt-1 text-sm font-bold">{selectedPage.updatedBy}</p></div></div>
        <div className="mt-8 border-t border-slate-100 pt-5"><p className="mb-3 text-[11px] font-bold uppercase tracking-wider text-slate-400">Page actions</p><div className="flex flex-wrap gap-2">{["Rename", "Move", "Duplicate", "Share", "Export", "Archive", "Delete"].map((action) => <button key={action} className="rounded-lg border border-slate-200 px-3 py-2 text-[12px] font-semibold text-slate-600 hover:border-violet-200 hover:text-violet-700">{action}</button>)}</div></div>
      </div></div>
  </main>;

  if (selectedSpace) return <main className="min-h-screen bg-[#fbfcff] px-5 py-6 text-slate-900 sm:px-9 lg:px-14"><div className="mx-auto max-w-6xl">
    <button onClick={() => setActiveSpace(null)} className="inline-flex items-center gap-1.5 text-[12px] font-semibold text-slate-500 hover:text-violet-700"><span>All Spaces</span><ChevronRight className="h-3.5 w-3.5" /><span className="text-slate-800">{selectedSpace.name}</span></button>
    <div className="mt-8 flex flex-wrap items-start justify-between gap-4"><div className="flex items-center gap-4"><span className={`grid h-13 w-13 place-items-center rounded-2xl ${colors.find((item) => item.value === selectedSpace.color)?.soft ?? "bg-violet-50 text-violet-600"}`}><Folder className="h-6 w-6 fill-current" /></span><div><h1 className="text-3xl font-bold tracking-tight">{selectedSpace.name}</h1><p className="mt-1 text-sm text-slate-500">{selectedSpace.pages.length} {selectedSpace.pages.length === 1 ? "page" : "pages"} · {selectedSpace.description}</p></div></div><div className="flex gap-2"><button onClick={openPageModal} className="inline-flex items-center gap-2 rounded-xl bg-violet-600 px-4 py-2.5 text-[12px] font-bold text-white shadow-lg shadow-violet-200 hover:bg-violet-700"><Plus className="h-4 w-4" />New Page</button><button className="grid h-10 w-10 place-items-center rounded-xl border border-slate-200 bg-white text-slate-500"><MoreHorizontal className="h-4 w-4" /></button></div></div>
    <section className="mt-8 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-[0_12px_35px_-25px_rgba(15,23,42,.45)]">{selectedSpace.pages.length === 0 ? <Empty title="This space is ready for its first page" detail="Create a page to capture plans, notes, research, and everything this space needs." action="Create Page" onAction={openPageModal} /> : <><div className="hidden grid-cols-[minmax(0,1.8fr)_1fr_1fr_.7fr_38px] gap-4 border-b border-slate-100 px-5 py-3 text-[10px] font-bold uppercase tracking-wider text-slate-400 md:grid"><span>Page name</span><span>Type / template</span><span>Last updated</span><span>Updated by</span><span /></div>{selectedSpace.pages.map((page) => <button key={page.id} onClick={() => setActivePage(page.id)} className="grid w-full grid-cols-[minmax(0,1fr)_auto] items-center gap-4 border-b border-slate-100 px-5 py-4 text-left last:border-0 hover:bg-violet-50/40 md:grid-cols-[minmax(0,1.8fr)_1fr_1fr_.7fr_38px]"><span className="flex min-w-0 items-center gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-violet-50 text-violet-600"><FileText className="h-4 w-4" /></span><span className="truncate text-[13px] font-bold text-slate-700">{page.name}</span></span><span className="hidden text-[12px] text-slate-500 md:block">{page.template}</span><span className="hidden text-[12px] text-slate-500 md:block">{page.updated}</span><span className="hidden text-[12px] font-semibold text-slate-600 md:block">{page.updatedBy}</span><Star onClick={(event) => { event.stopPropagation(); togglePageFavorite(page.id); }} className={`h-4 w-4 cursor-pointer ${page.favorite ? "fill-amber-400 text-amber-400" : "text-slate-300"}`} /></button>)}</>}</section>
  </div>{showPageModal && <PageModal close={() => setShowPageModal(false)} name={pageName} setName={setPageName} template={pageTemplate} setTemplate={setPageTemplate} target={pageSpace} setTarget={setPageSpace} spaces={spaces} submit={createPage} />}</main>;

  return <main className="min-h-screen bg-[#fbfcff] px-5 py-6 text-slate-900 sm:px-9 lg:px-14"><div className="mx-auto max-w-6xl">
    <header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[11px] font-bold uppercase tracking-[.16em] text-violet-600">Workspace</p><h1 className="mt-1 text-3xl font-bold tracking-tight">All Spaces</h1><p className="mt-1 text-sm text-slate-500">{spaces.length} {spaces.length === 1 ? "space" : "spaces"}</p></div><div className="flex gap-2"><button onClick={openPageModal} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-[12px] font-bold text-slate-700 hover:border-violet-200"><FileText className="h-4 w-4 text-violet-600" />New Page</button><button onClick={() => setShowSpaceModal(true)} className="inline-flex items-center gap-2 rounded-xl bg-violet-600 px-4 py-2.5 text-[12px] font-bold text-white shadow-lg shadow-violet-200 hover:bg-violet-700"><Plus className="h-4 w-4" />New Space</button></div></header>
    <div className="mt-8 flex flex-col gap-4 rounded-2xl border border-slate-200 bg-white p-3 shadow-sm lg:flex-row lg:items-center"><label className="flex flex-1 items-center gap-2 rounded-xl bg-slate-50 px-3 py-2.5 text-slate-400"><Search className="h-4 w-4" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search spaces or pages..." className="w-full bg-transparent text-[13px] text-slate-700 outline-none placeholder:text-slate-400" /></label><div className="flex items-center gap-1 overflow-x-auto">{["All Spaces", "Favorites", "Recently Opened", "Archived"].map((item) => <button key={item} onClick={() => setFilter(item)} className={`whitespace-nowrap rounded-lg px-3 py-2 text-[11px] font-bold ${filter === item ? "bg-violet-100 text-violet-700" : "text-slate-500 hover:bg-slate-50"}`}>{item}</button>)}</div><div className="flex items-center gap-1 border-l border-slate-100 pl-2"><button onClick={() => setView("grid")} className={`grid h-8 w-8 place-items-center rounded-lg ${view === "grid" ? "bg-violet-50 text-violet-600" : "text-slate-400"}`}><Grid2X2 className="h-4 w-4" /></button><button onClick={() => setView("list")} className={`grid h-8 w-8 place-items-center rounded-lg ${view === "list" ? "bg-violet-50 text-violet-600" : "text-slate-400"}`}><LayoutList className="h-4 w-4" /></button><label className="ml-1 flex items-center gap-1 text-[11px] font-semibold text-slate-500"><Settings2 className="h-3.5 w-3.5" /><select value={sort} onChange={(event) => setSort(event.target.value)} className="bg-transparent outline-none"><option>Recently Updated</option><option>Name</option><option>Most Pages</option><option>Favorites</option></select></label></div></div>
    <section className={`mt-6 ${view === "grid" ? "grid gap-4 sm:grid-cols-2 xl:grid-cols-3" : "space-y-3"}`}>{filteredSpaces.length === 0 ? <div className="col-span-full rounded-2xl border border-dashed border-slate-300 bg-white"><Empty title={spaces.length ? "No spaces match your view" : "Create your first space"} detail={spaces.length ? "Try changing your search or filters." : "Spaces are top-level folders for the pages and work you want to keep together."} action="New Space" onAction={() => setShowSpaceModal(true)} /></div> : filteredSpaces.map((space) => <button key={space.id} onClick={() => setActiveSpace(space.id)} className={`group rounded-2xl border border-slate-200 bg-white p-5 text-left shadow-[0_10px_25px_-22px_rgba(15,23,42,.45)] transition hover:-translate-y-0.5 hover:border-violet-200 hover:shadow-lg ${view === "list" ? "flex items-center gap-4" : ""}`}><span className={`grid h-11 w-11 shrink-0 place-items-center rounded-xl ${colors.find((item) => item.value === space.color)?.soft ?? "bg-violet-50 text-violet-600"}`}><Folder className="h-5 w-5 fill-current" /></span><div className={view === "list" ? "min-w-0 flex-1" : "mt-5"}><div className="flex items-start justify-between gap-3"><h2 className="truncate text-[15px] font-bold">{space.name}</h2><div className="flex items-center"><Star onClick={(event) => { event.stopPropagation(); toggleSpaceFavorite(space.id); }} className={`h-4 w-4 cursor-pointer ${space.favorite ? "fill-amber-400 text-amber-400" : "text-slate-300 hover:text-amber-400"}`} /><MoreHorizontal className="ml-2 h-4 w-4 text-slate-300" /></div></div><p className="mt-2 line-clamp-2 text-[12px] leading-5 text-slate-500">{space.description}</p><div className="mt-5 flex items-center justify-between text-[11px] text-slate-400"><span>{space.pages.length} {space.pages.length === 1 ? "Page" : "Pages"}</span><span>Updated {space.updated}</span></div></div></button>)}</section>
  </div>{showSpaceModal && <Modal onClose={() => setShowSpaceModal(false)}><h2 className="text-lg font-bold">Create a new space</h2><p className="mt-1 text-[12px] text-slate-500">Start a home for related pages and collaborators.</p><div className="mt-5 space-y-4"><Field label="Space name" value={spaceName} setValue={setSpaceName} placeholder="e.g. Product Launch" /><Field label="Description" value={spaceDescription} setValue={setSpaceDescription} placeholder="What belongs in this space?" /><div><p className="mb-2 text-[12px] font-bold text-slate-700">Color</p><div className="flex gap-2">{colors.map((item) => <button key={item.value} onClick={() => setColor(item.value)} title={item.name} className={`h-8 w-8 rounded-full ${item.value} ring-offset-2 ${color === item.value ? "ring-2 ring-violet-500" : ""}`} />)}</div></div><button onClick={createSpace} className="w-full rounded-xl bg-violet-600 py-3 text-[12px] font-bold text-white hover:bg-violet-700">Create Space</button></div></Modal>}{showPageModal && <PageModal close={() => setShowPageModal(false)} name={pageName} setName={setPageName} template={pageTemplate} setTemplate={setPageTemplate} target={pageSpace} setTarget={setPageSpace} spaces={spaces} submit={createPage} />}</main>;
}

function Empty({ title, detail, action, onAction }: { title: string; detail: string; action: string; onAction: () => void }) { return <div className="flex min-h-72 flex-col items-center justify-center p-8 text-center"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-violet-50 text-violet-600"><Folder className="h-6 w-6" /></span><h2 className="mt-4 text-[15px] font-bold">{title}</h2><p className="mt-1 max-w-sm text-[12px] leading-5 text-slate-500">{detail}</p><button onClick={onAction} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-violet-600 px-4 py-2.5 text-[12px] font-bold text-white"><Plus className="h-4 w-4" />{action}</button></div>; }
function Field({ label, value, setValue, placeholder }: { label: string; value: string; setValue: (value: string) => void; placeholder: string }) { return <label className="block"><span className="mb-1.5 block text-[12px] font-bold text-slate-700">{label}</span><input value={value} onChange={(event) => setValue(event.target.value)} placeholder={placeholder} className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-[13px] outline-none placeholder:text-slate-400 focus:border-violet-400 focus:ring-2 focus:ring-violet-100" /></label>; }
function PageModal({ close, name, setName, template, setTemplate, target, setTarget, spaces, submit }: { close: () => void; name: string; setName: (value: string) => void; template: string; setTemplate: (value: string) => void; target: number | ""; setTarget: (value: number | "") => void; spaces: Space[]; submit: () => void }) { return <Modal onClose={close}><h2 className="text-lg font-bold">Create a new page</h2><p className="mt-1 text-[12px] text-slate-500">Add a page to a space, then make it your own.</p><div className="mt-5 space-y-4"><Field label="Page name" value={name} setValue={setName} placeholder="e.g. Sprint planning" /><label className="block"><span className="mb-1.5 block text-[12px] font-bold text-slate-700">Add to space</span><select value={target} onChange={(event) => setTarget(event.target.value ? Number(event.target.value) : "")} className="w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-[13px] outline-none focus:border-violet-400"><option value="">Select a space</option>{spaces.map((space) => <option key={space.id} value={space.id}>{space.name}</option>)}</select></label><label className="block"><span className="mb-1.5 block text-[12px] font-bold text-slate-700">Template</span><select value={template} onChange={(event) => setTemplate(event.target.value)} className="w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-[13px] outline-none focus:border-violet-400">{templates.map((item) => <option key={item}>{item}</option>)}</select></label><button disabled={!spaces.length} onClick={submit} className="w-full rounded-xl bg-violet-600 py-3 text-[12px] font-bold text-white hover:bg-violet-700 disabled:cursor-not-allowed disabled:bg-slate-200">Create Page</button>{!spaces.length && <p className="text-center text-[11px] text-slate-400">Create a space before adding a page.</p>}</div></Modal>; }
